name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.1

      - name: Install asdf dependencies
        uses: asdf-vm/actions/install@v3.0.2

      - name: Run ShellCheck
        run: scripts/shellcheck.bash

      - name: Run shfmt
        run: scripts/shfmt.bash

  integration-test:
    needs: lint
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup JDK
        uses: actions/setup-java@v4.4.0
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Test integration with asdf
        uses: asdf-vm/actions/plugin-test@v3.0.2
        with:
          command: aaw version
